import { loadFontBytes, type LoadedFont } from './fonts'

export type GoogleFontStyle = 'regular' | '700' | 'italic' | '700italic'

export const GOOGLE_FONT_STYLES: { value: GoogleFontStyle; label: string }[] = [
  { value: 'regular', label: 'Normal' },
  { value: '700', label: 'Bold' },
  { value: 'italic', label: 'Italic' },
  { value: '700italic', label: 'Bold Italic' },
]

interface FamilyEntry {
  category: string
  variants: Partial<Record<GoogleFontStyle, string>>
}

type Manifest = Record<string, FamilyEntry>

let manifestPromise: Promise<Manifest> | null = null

// Lazily load the prebuilt manifest (web-preview/src/assets/google-fonts-manifest.json,
// generated by scripts/build-google-fonts-manifest.mjs). Dynamic import keeps
// it out of the main bundle until the Google Fonts picker is opened.
function loadManifest(): Promise<Manifest> {
  manifestPromise ??= import('../assets/google-fonts-manifest.json').then((m) => m.default as Manifest)
  return manifestPromise
}

// Return up to `limit` family names matching `query` (case-insensitive
// substring match), sorted alphabetically.
export async function searchGoogleFonts(query: string, limit = 20): Promise<string[]> {
  const manifest = await loadManifest()
  const q = query.trim().toLowerCase()
  const names = Object.keys(manifest)
  if (!q) return names.slice(0, limit)
  return names.filter((name) => name.toLowerCase().includes(q)).slice(0, limit)
}

// Return the styles available for `family` (always includes "regular" for
// any family present in the manifest).
export async function stylesForFamily(family: string): Promise<GoogleFontStyle[]> {
  const manifest = await loadManifest()
  const entry = manifest[family]
  if (!entry) return []
  return GOOGLE_FONT_STYLES.map((s) => s.value).filter((style) => entry.variants[style])
}

const fontCache = new Map<string, Promise<LoadedFont>>()

// Fetch the .ttf bytes for `family`/`style` from fonts.gstatic.com (CORS-
// enabled) and register them as a usable font, caching by family+style so
// repeated selections don't re-download.
export async function fetchGoogleFont(family: string, style: GoogleFontStyle): Promise<LoadedFont> {
  const key = `${family}::${style}`
  let promise = fontCache.get(key)
  if (!promise) {
    promise = (async () => {
      const manifest = await loadManifest()
      const url = manifest[family]?.variants[style]
      if (!url) throw new Error(`Stilul "${style}" nu este disponibil pentru fontul "${family}".`)
      const res = await fetch(url)
      if (!res.ok) throw new Error(`Nu s-a putut descărca fontul "${family}" (${res.status}).`)
      const buffer = await res.arrayBuffer()
      return loadFontBytes(buffer, `${family} ${style}.ttf`)
    })()
    fontCache.set(key, promise)
  }
  return promise
}
