import { loadFontBytes, type LoadedFont } from './fonts'
import { m } from '../paraglide/messages'

export type GoogleFontStyle = 'regular' | '700' | 'italic' | '700italic'

export const GOOGLE_FONT_STYLES: { value: GoogleFontStyle; label: string }[] = [
  { value: 'regular', label: m.fonts_style_regular() },
  { value: '700', label: m.fonts_style_bold() },
  { value: 'italic', label: m.fonts_style_italic() },
  { value: '700italic', label: m.fonts_style_bold_italic() },
]

interface FamilyEntry {
  category: string
  variants: Partial<Record<GoogleFontStyle, string>>
  // Present and true when the family's embedded static .ttf includes Google's
  // `latin-ext` subset (covers Romanian ș ț ă). Omitted when unsupported.
  latinExt?: boolean
}

type Manifest = Record<string, FamilyEntry>

let manifestPromise: Promise<Manifest> | null = null

// Lazily load the prebuilt manifest (web-preview/src/assets/google-fonts-manifest.json,
// generated by scripts/build-google-fonts-manifest.mjs). Dynamic import keeps
// it out of the main bundle until the Google Fonts picker is opened.
function loadManifest(): Promise<Manifest> {
  manifestPromise ??= import('../assets/google-fonts-manifest.json').then((m) => m.default as Manifest)
  return manifestPromise
}

// Return up to `limit` family names matching `query` (case-insensitive
// substring match), sorted alphabetically.
export async function searchGoogleFonts(query: string, limit = 20): Promise<string[]> {
  const manifest = await loadManifest()
  const q = query.trim().toLowerCase()
  const names = Object.keys(manifest)
  if (!q) return names.slice(0, limit)
  return names.filter((name) => name.toLowerCase().includes(q)).slice(0, limit)
}

// Return the styles available for `family` (always includes "regular" for
// any family present in the manifest).
export async function stylesForFamily(family: string): Promise<GoogleFontStyle[]> {
  const manifest = await loadManifest()
  const entry = manifest[family]
  if (!entry) return []
  return GOOGLE_FONT_STYLES.map((s) => s.value).filter((style) => entry.variants[style])
}

// Whether `family`'s embedded font covers the Latin-Extended subset, which
// holds the Romanian diacritics (ș ț ă). Unknown families (e.g. before the
// manifest is regenerated with the flag) report false. The picker uses this to
// warn that Romanian text may render with missing glyphs.
export async function familySupportsLatinExt(family: string): Promise<boolean> {
  const manifest = await loadManifest()
  return manifest[family]?.latinExt === true
}

// Fixed sample shown for each font in the picker preview.
export const PREVIEW_SAMPLE = 'Qarg09!'

// Build a Google Fonts CSS2 stylesheet URL that loads `families` (regular/400)
// subsetted to just the glyphs in `text`, so only a few KB download per font.
// Returns '' for an empty list. The fonts register under their real family
// names, so the picker can render the sample via `font-family: "<family>"`.
export function googleFontsCss2Url(families: string[], text: string = PREVIEW_SAMPLE): string {
  const unique = Array.from(new Set(families.filter((f) => f.trim() !== '')))
  if (unique.length === 0) return ''
  const params = unique.map((f) => `family=${encodeURIComponent(f)}`).join('&')
  return `https://fonts.googleapis.com/css2?${params}&text=${encodeURIComponent(text)}&display=swap`
}

const fontCache = new Map<string, Promise<LoadedFont>>()

// Persistent (cross-reload) cache of the downloaded font responses, keyed by
// their immutable fonts.gstatic.com URL. The version suffix lets us invalidate
// it later if the stored representation ever changes.
const FONT_CACHE_NAME = 'pdfcodes-google-fonts-v1'

// Ask the browser, once, to mark this origin's storage as persistent so the
// cached fonts aren't evicted under storage pressure. Best-effort: it may be
// denied or unsupported, which is fine — the cache still works, just evictable.
let persistRequested = false
function requestPersistentStorage(): void {
  if (persistRequested) return
  persistRequested = true
  void navigator.storage?.persist?.().catch(() => {})
}

// Fetch the .ttf bytes for `url`, preferring the persistent Cache Storage so a
// font downloaded once is reused across reloads/sessions (fonts rarely change,
// and gstatic URLs are content-addressed). Falls back to a plain network fetch
// where the Cache API is unavailable (non-secure context, private mode, older
// browsers). `family` is only used for the error message.
async function fetchFontBytes(url: string, family: string): Promise<ArrayBuffer> {
  if (typeof caches === 'undefined') {
    const res = await fetch(url)
    if (!res.ok) throw new Error(m.fonts_download_failed({ family, status: res.status }))
    return res.arrayBuffer()
  }
  const cache = await caches.open(FONT_CACHE_NAME)
  let res = await cache.match(url)
  if (!res) {
    res = await fetch(url)
    if (!res.ok) throw new Error(m.fonts_download_failed({ family, status: res.status }))
    requestPersistentStorage()
    // Best-effort persist; ignore quota/storage failures and keep the bytes.
    try {
      await cache.put(url, res.clone())
    } catch { /* storage full or unavailable — fall through with the fetched bytes */ }
  }
  return res.arrayBuffer()
}

// Fetch the .ttf bytes for `family`/`style` from fonts.gstatic.com (CORS-
// enabled) and register them as a usable font. Two cache layers: an in-memory
// promise map (same-session re-selection) and persistent Cache Storage (across
// reloads), so a given font is downloaded over the network at most once ever.
export async function fetchGoogleFont(family: string, style: GoogleFontStyle): Promise<LoadedFont> {
  const key = `${family}::${style}`
  let promise = fontCache.get(key)
  if (!promise) {
    promise = (async () => {
      const manifest = await loadManifest()
      const url = manifest[family]?.variants[style]
      if (!url) throw new Error(`Stilul "${style}" nu este disponibil pentru fontul "${family}".`)
      const buffer = await fetchFontBytes(url, family)
      return loadFontBytes(buffer, `${family} ${style}.ttf`)
    })()
    fontCache.set(key, promise)
  }
  return promise
}
